#!/bin/bash

set -e

HA_DIR=$(pwd)
SETUP_DIR=${HA_DIR}/scripts

if [ "$(whoami)" == "root" ]; then
  source ${SETUP_DIR}/0/script.sh
else
  if [ -n "$1"  ]; then
    STEP=${1}
  else
    STEP=1
  fi
  if [ $STEP -lt 2 ]; then
    source ${SETUP_DIR}/1/script.sh
  fi

  if [ $STEP -lt 3 ]; then
    source ${SETUP_DIR}/2/script.sh
  fi

  if [ $STEP -lt 4 ]; then
    source ${SETUP_DIR}/3/script.sh
  fi

  if [ $STEP -lt 5 ]; then
    source ${SETUP_DIR}/4/script.sh
  fi

  if [ $STEP -lt 6 ]; then
    source ${SETUP_DIR}/5/script.sh
  fi
fi

