#!/bin/bash

set -e

HA_DIR=$(pwd)
SETUP_DIR=${HA_DIR}/scripts

if [ "$(whoami)" == "root" ]; then
  source ${SETUP_DIR}/0/script.sh
else
  source ${SETUP_DIR}/1/script.sh
  source ${SETUP_DIR}/2/script.sh
  source ${SETUP_DIR}/3/script.sh
  source ${SETUP_DIR}/4/script.sh
  source ${SETUP_DIR}/5/script.sh
fi

