#!/bin/bash

if [ -z "${1}" ]; then
  read -p "Please enter app-name: " APP_NAME
else
  APP_NAME=${1}
fi

if [ -f ~/nextappid ]; then
  APP_ID=$(cat ~/nextappid)
else
  APP_ID=1
fi

SETUP_FOLDER=/usr/local/lib/host-app/new
GIT_FOLDER=${HOME}/repo/${APP_NAME}.git
USERNAME=$(whoami)
HOOK=hooks/post-receive
APP_FOLDER=${HOME}/apps/${APP_NAME}
APP_PORT=$(( APP_ID + 8000 ))
FQDN=$(hostname -f)
DOMAIN=${APP_NAME}.${FQDN}

echo "Initiating app"
mkdir ${GIT_FOLDER}
cd ${GIT_FOLDER}
git init --bare

echo "Cloning app"
cd ~/apps/
git clone ${GIT_FOLDER}
cd ${APP_NAME}

echo "Installing startup app"
cp ${SETUP_FOLDER}/start.js ./start.js
cp ${SETUP_FOLDER}/pm2.json ./pm2.json
sed -i 's/{{PORT}}/'"${APP_PORT}"'/g' ./pm2.json
sed -i 's/{{USERNAME}}/'"${USERNAME}"'/g' ./pm2.json
sed -i 's/{{APP_NAME}}/'"${APP_NAME}"'/g' ./pm2.json
sed -i 's/{{FQDN}}/'"${FQDN}"'/g' ./pm2.json

echo "pushing first commit"
git add .
git commit -m "init"
git push -u origin master

echo "Installing git server hook"
cp ${SETUP_FOLDER}/post-receive.sample ${HOOK}
sed -i 's/{{APP_NAME}}/'"${APP_NAME}"'/g' ${HOOK}
chmod +x ${HOOK}

echo "Starting app"
pm2 start ${APP_FOLDER}/pm2.json

echo "Adding app to startup"
pm2 save

echo "Adding nginx config"
sudo /usr/local/lib/host-app/add-nginx-config ${APP_NAME} ${APP_PORT}

echo "Update app id for next app"
NEXT_ID=$(( APP_ID + 1 ))
echo $NEXT_ID > ~/nextappid
