#!/bin/bash

function set_app_name {
  if [ -z "$1" ]; then
    read -p "Please provide app-name: " APP_NAME
  else
    APP_NAME=$1
  fi
  export APP_NAME
}

USR_FOLDER=/usr/local/lib/host-app

case "$1" in
  new)
    set_app_name $2;
    sudo ${USR_FOLDER}/create-new $APP_NAME;
    ;;
  update)
    set_app_name $2;
    sudo ${USR_FOLDER}/update-app $APP_NAME;
    ;;
  update-host)
    sudo ${USR_FOLDER}/update-hostapp;
    ;;
  *)
    echo "ha new <app-name>"
    echo "ha update <app-name>"
    echo "ha update-host"
    ;;
esac
